### ISSUE TITLE
MSYS2: Unattended install via Packer hangs after "SYSTEM UPDATE 3" step

### ISSUE THREAD

**Issue by fabiendelpierre** [chocolatey/chocolatey-coreteampackages#1176]
Hi there,

## Context

I'm trying to install Ruby and MSYS2 onto a Windows Server 2016 instance. I want to do it with Packer because ultimately I'm putting together an AWS AMI to be used in an autoscaling group. In the end this is supposed to be a Jenkins slave node. I have extra steps in the Packer build to install Java and a Jenkins swarm client, but I've removed those bits for troubleshooting.

And the reason I (seem to) need MSYS2 is because I need to install a couple of gems after Ruby is installed. 

I'm woefully unfamiliar with Ruby in Windows, and quite rusty with Windows itself so perhaps there's something I'm missing...

It might well be an issue with Packer rather than this package, but I figured I'd start here.

If I create a Windows instance in AWS manually, remote into it, open a Powershell window and run the following commands, it works fine:

```
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install ruby --version 2.5.3.101 -y
choco install msys2 -y
```

However, when running the same commands within Packer, it hangs after the step titled "SYSTEM UPDATE 3". This is the output I get:

```
    ...
    amazon-ebs: ================= SYSTEM UPDATE 3 =================
    amazon-ebs:
    amazon-ebs: :: Synchronizing package databases...
    amazon-ebs:  mingw32 is up to date
    amazon-ebs:  mingw64 is up to date
    amazon-ebs:  msys is up to date
    amazon-ebs: :: Starting core system upgrade...
    amazon-ebs:  there is nothing to do
    amazon-ebs: :: Starting full system upgrade...
    amazon-ebs:  there is nothing to do
    amazon-ebs: Only an exit code of non-zero will fail the package by default. Set
    amazon-ebs:  `--failonstderr` if you want error messages to also fail a script. See
    amazon-ebs:  `choco -h` for details.
    amazon-ebs: Environment Vars (like PATH) have changed. Close/reopen your shell to
    amazon-ebs:  see the changes (or in powershell/cmd.exe just type `refreshenv`).
    amazon-ebs:  The install of msys2 was successful.
    amazon-ebs:   Software installed to 'C:\tools\msys64'
    amazon-ebs:
    amazon-ebs: Chocolatey installed 1/1 packages.
    amazon-ebs:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

In my manual Powershell window, I get the exact same output (minus the "amazon-ebs:" prefixing each line -- this is what comes out of Packer), except I get returned to the shell. When Packer does the same thing, it just sits there instead of proceeding with the next steps of the script. Not sure why. I've tried waiting a long time, in case it's doing something invisible, but hours later it's still just sitting there. And again, when I run this manually, I'm back at the shell immediately after MSYS2 is done installing.

I've tried adding an `exit 0` to the Packer script, to no avail (didn't have much hope that would work but it was worth a shot). I wasn't sure if perhaps your script is returning an unexpected exit code, but I looked at the [code](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/msys2/tools/chocolateyinstall.ps1) and saw nothing of the sort (and normally Packer would see anything but a 0 as an error and the build would fail).

FWIW I've also tried specifying a different version of Ruby (2.4.3.1) as well as no version, but that changed nothing.

I also tried with the current AMI of Windows Server 2012 R2 (instead of 2016), but got the same result.

## Steps to Reproduce (for bugs)
Here's my Packer script: https://gist.github.com/fabiendelpierre/60040a38b645fba36e6ac3a52e65b8bc
Note there is also a user data script, I included it because it's called by the Packer script, but I don't think it's relevant to the issue.
I hope you have a way of testing this in AWS, since that's the only way I can reproduce the issue.
If you're not familiar with Packer, here are more detailed steps:
1. Install [Packer](https://www.packer.io/downloads.html)
2. Save the JSON file in the gist to your machine
3. In the folder where you saved the JSON file, create a `scripts` subdirectory, then save the Powershell file from the Gist to this subdirectory, calling the file ec2-userdata.ps1 (or save it however you like and edit the Packer script as you like -- it's self-explanatory)
4. Edit the `subnet_id` line at the top with a valid AWS subnet ID.
5. Run Packer with: `packer build file.json`

## Your Environment

* Package Version used: 20180531.0.0
* Operating System and version: Windows Server 2016 image provided by AWS, ami-041114ddee4a98333 in us-east-1
* Chocolatey version: 0.10.11
* Install gist: https://gist.github.com/fabiendelpierre/984f8fabbb425e6b2dfbdf0e7e66a345

Let me know if you have any questions - many thanks for reading!
